### ISSUE TITLE
Pixiv Search Tool

### ISSUE THREAD

**Issue by seventhsky** [FlandreDaisuki/Userscript-Exercise#1]
搜尋指定長寬比時會出錯，無法搜尋其他的長寬比選項，過濾出來的結果全都會是正方形。
![1](https://cloud.githubusercontent.com/assets/12661302/10926538/4e8dc03a-82d3-11e5-831d-753aded03e5f.png)
![2](https://cloud.githubusercontent.com/assets/12661302/10926537/4e8d9cf4-82d3-11e5-82f2-62311923eff9.png)

**Comment by FlandreDaisuki** [comment]
已修正。謝謝回報。(居然有人用 好感動www
在GreaseMonkey右鍵Script強制更新可以直接更新到2015.11.04版
或是看我diff的部份自己改程式碼(強制更新會造成你之前自己調過參數不見，如 UC_following_style)

**Comment by seventhsky** [comment]
修正得好快！再回報一個問題
設定從日期較早的開始搜尋，過濾結果還是會從新的開始
![3](https://cloud.githubusercontent.com/assets/12661302/10936430/972ffa34-8327-11e5-8237-afbedbf278fc.png)
![4](https://cloud.githubusercontent.com/assets/12661302/10936432/97321940-8327-11e5-8297-dc5fe505df1d.png)
其實我找這種Script好一陣子了，Pixiv++功能太雜，像這樣精簡的我覺得很棒。
