### ISSUE TITLE
Pixiv Search Tool 日期排序

### ISSUE THREAD

**Issue by seventhsky** [FlandreDaisuki/Userscript-Exercise#2]
修正得好快！再回報一個問題
設定從日期較早的開始搜尋，過濾結果還是會從新的開始
![3](https://cloud.githubusercontent.com/assets/12661302/10936430/972ffa34-8327-11e5-8237-afbedbf278fc.png)
![4](https://cloud.githubusercontent.com/assets/12661302/10936432/97321940-8327-11e5-8297-dc5fe505df1d.png)
其實我找這種Script好一陣子了，Pixiv++功能太雜，像這樣精簡的我覺得很棒。

**Comment by seventhsky** [comment]
另外有時有些關鍵字過濾會變成空白的
![5](https://cloud.githubusercontent.com/assets/12661302/10946590/fef9c678-835d-11e5-937a-4ef87b31349b.png)
![6](https://cloud.githubusercontent.com/assets/12661302/10946589/fef91fac-835d-11e5-91b4-c0488c34897a.png)

**Comment by FlandreDaisuki** [comment]
已修正，謝謝回報。(2015.11.05)
我也覺得Pixiv++不太會用才寫這個的，自己用超方便
可能沒用到別的設定沒發現有這麼多Bug ^_^
