### ISSUE TITLE
Pixiv Search Tool被隱藏的部分

### ISSUE THREAD

**Issue by seventhsky** [FlandreDaisuki/Userscript-Exercise#3]
熱門度搜索試用
![1](https://cloud.githubusercontent.com/assets/12661302/11463867/4b794668-9763-11e5-92fa-fc93514cd894.png)
搜尋結果的隨機推薦
![3](https://cloud.githubusercontent.com/assets/12661302/11463876/62d7e102-9763-11e5-82fb-0e813fe3c8f0.png)
看圖的隨機推薦
![2](https://cloud.githubusercontent.com/assets/12661302/11463866/4b784fba-9763-11e5-88e4-67d1f2d1eb9b.png)
可以讓它顯示出來嗎？

**Comment by FlandreDaisuki** [comment]
1. 因為我想那個"熱門度查詢"試用的功能，就是這個插件想要做到的事
也就是若已經有"熱門度查詢"功能的帳號，基本上用這個插件反而畫蛇添足了

# 若還是希望看到 將line52的 '.ad-printservice', 整行刪掉即可

2. 同理，但這個推薦的通常都是舊的或極高人氣的經典
所以我是利用tag "xxx 100 user" 或 日期順 加上這個差件來找的
又我覺得用這插件的同時出現一條黃黃的不是很整齊 所以才刪掉的

# 若還是希望看到 將line56的 '.popular-introduction' 整行刪掉即可

3. 這個可能就有困難了，因為程式實作的關係，在圖片頁不會有問題，但這個推薦出現在搜尋頁或其他頁面會有問題，可能要等有空再去改程式碼才能辦到

btw 謝謝回報

**Comment by seventhsky** [comment]
"pixiv漫畫上的焦點漫畫"可以隱藏起來嗎？
另外最近常常過濾到一半就會卡住，不知道原因。

**Comment by FlandreDaisuki** [comment]
ads裡面補個 '.comic-hot-works' 試試看

```
PST.ads = [
    '.ad',
    '.ads_area',
    '.ad-footer',
    '.ads_anchor',
    '.user-ad-container',
    '.ads_area_no_margin',
    '.comic-hot-works'
];
```
也有可能是P網有更新，最近比較忙沒時間弄
改天想重寫個w
